In [59]:
import numpy as np
import pandas as pd

### Question 1

In [15]:
np.__version__

'1.20.3'

### Question 2

In [17]:
pd.__version__

'1.3.2'

### Question 3

In [20]:
df = pd.read_csv('data.csv')

In [21]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [26]:
df[df['Make'] == 'BMW'].MSRP.mean()

61546.76347305389

### Question 4

In [30]:
df[df['Year'] >= 2015]['Engine HP'].isna().sum()

51

### Question 5

In [62]:
round(df[df['Year'] >= 2015]['Engine HP'].mean())

273

In [35]:
df[df['Year'] >= 2015]['Engine HP'].fillna(df[df['Year'] >= 2015]['Engine HP'].mean()).mean()

272.98771870794116

### Question 6

Select all the "Rolls-Royce" cars from the dataset.

In [61]:
df[df['Make'] == 'Rolls-Royce'].head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [39]:
df[df['Make'] == 'Rolls-Royce'][['Engine HP', 'Engine Cylinders', 'highway MPG']]

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [40]:
df[df['Make'] == 'Rolls-Royce'][['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [41]:
X = df[df['Make'] == 'Rolls-Royce'][['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates().to_numpy()

In [42]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [44]:
XTX = X.T.dot(X)

In [45]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [48]:
np.linalg.inv(XTX)

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [50]:
sum(sum(np.linalg.inv(XTX)))

0.032212320677486195

### Question 7

In [51]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [52]:
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [56]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)

In [57]:
w

array([ 0.19989598, 31.02612262, 31.65378877])